apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: shared
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
    - app-backend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  namespace: shared
  labels:
    app: frontend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
    - app-frontend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluent-bit-monitor
  namespace: shared
  labels:
    app: fluent-bit
    release: prometheus
spec:
  selector:
    matchLabels:
      app: fluent-bit
  namespaceSelector:
    matchNames:
    - shared
  endpoints:
  - port: http
    path: /api/v1/metrics/prometheus
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-monitor
  namespace: shared
  labels:
    app: prometheus
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  namespaceSelector:
    matchNames:
    - shared
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
