apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-backend

bases:
  - ../../base

resources:
  - backend-config.yaml
  - ../../base/postgres-deployment.yaml
  - ../../base/redis-deployment.yaml

configMapGenerator:
  - name: backend-config
    behavior: replace
    files:
      - backend-config.yaml

labels:
  - pairs:
      deployment-mode: onprem
      environment: production
