apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-backend

bases:
  - ../../base

resources:
  - backend-config.yaml
  - azure-secrets.yaml

configMapGenerator:
  - name: backend-config
    behavior: replace
    files:
      - backend-config.yaml

patchesStrategicMerge:
  - backend-patch.yaml

labels:
  - pairs:
      deployment-mode: azure
      environment: production
