apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ai-saas-dashboard
data:
  FLASK_ENV: "production"
  POSTGRES_DB: "ai_saas"
  POSTGRES_USER: "postgres"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
