apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../namespaces/namespaces.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

# These are only included in on-premise overlay
# - postgres-deployment.yaml
# - redis-deployment.yaml
